// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ClessLi/component-base/pkg/client-sdk/http/v1 (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -self_package=github.com/ClessLi/component-base/pkg/client-sdk/http/v1 -destination=mock_client.go -package=v1 github.com/ClessLi/component-base/pkg/client-sdk/http/v1 Client
//

// Package v1 is a generated GoMock package.
package v1

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient[REQ any, RESP any] struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder[REQ, RESP]
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder[REQ any, RESP any] struct {
	mock *MockClient[REQ, RESP]
}

// NewMockClient creates a new mock instance.
func NewMockClient[REQ any, RESP any](ctrl *gomock.Controller) *MockClient[REQ, RESP] {
	mock := &MockClient[REQ, RESP]{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder[REQ, RESP]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient[REQ, RESP]) EXPECT() *MockClientMockRecorder[REQ, RESP] {
	return m.recorder
}

// Endpoint mocks base method.
func (m *MockClient[REQ, RESP]) Endpoint() Endpoint[REQ, RESP] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Endpoint")
	ret0, _ := ret[0].(Endpoint[REQ, RESP])
	return ret0
}

// Endpoint indicates an expected call of Endpoint.
func (mr *MockClientMockRecorder[REQ, RESP]) Endpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Endpoint", reflect.TypeOf((*MockClient[REQ, RESP])(nil).Endpoint))
}
