// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ClessLi/component-base/pkg/client-sdk/http/v1 (interfaces: Client,ClientBuilder)
//
// Generated by this command:
//
//	mockgen -self_package=github.com/ClessLi/component-base/pkg/client-sdk/http/v1 -destination=mock_client.go -package=v1 github.com/ClessLi/component-base/pkg/client-sdk/http/v1 Client,ClientBuilder
//

// Package v1 is a generated GoMock package.
package v1

import (
	reflect "reflect"

	http "github.com/go-kit/kit/transport/http"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient[REQ any, RESP any] struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder[REQ, RESP]
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder[REQ any, RESP any] struct {
	mock *MockClient[REQ, RESP]
}

// NewMockClient creates a new mock instance.
func NewMockClient[REQ any, RESP any](ctrl *gomock.Controller) *MockClient[REQ, RESP] {
	mock := &MockClient[REQ, RESP]{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder[REQ, RESP]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient[REQ, RESP]) EXPECT() *MockClientMockRecorder[REQ, RESP] {
	return m.recorder
}

// Endpoint mocks base method.
func (m *MockClient[REQ, RESP]) Endpoint() Endpoint[REQ, RESP] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Endpoint")
	ret0, _ := ret[0].(Endpoint[REQ, RESP])
	return ret0
}

// Endpoint indicates an expected call of Endpoint.
func (mr *MockClientMockRecorder[REQ, RESP]) Endpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Endpoint", reflect.TypeOf((*MockClient[REQ, RESP])(nil).Endpoint))
}

// MockClientBuilder is a mock of ClientBuilder interface.
type MockClientBuilder[REQ any, RESP any] struct {
	ctrl     *gomock.Controller
	recorder *MockClientBuilderMockRecorder[REQ, RESP]
	isgomock struct{}
}

// MockClientBuilderMockRecorder is the mock recorder for MockClientBuilder.
type MockClientBuilderMockRecorder[REQ any, RESP any] struct {
	mock *MockClientBuilder[REQ, RESP]
}

// NewMockClientBuilder creates a new mock instance.
func NewMockClientBuilder[REQ any, RESP any](ctrl *gomock.Controller) *MockClientBuilder[REQ, RESP] {
	mock := &MockClientBuilder[REQ, RESP]{ctrl: ctrl}
	mock.recorder = &MockClientBuilderMockRecorder[REQ, RESP]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientBuilder[REQ, RESP]) EXPECT() *MockClientBuilderMockRecorder[REQ, RESP] {
	return m.recorder
}

// Build mocks base method.
func (m *MockClientBuilder[REQ, RESP]) Build() Client[REQ, RESP] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build")
	ret0, _ := ret[0].(Client[REQ, RESP])
	return ret0
}

// Build indicates an expected call of Build.
func (mr *MockClientBuilderMockRecorder[REQ, RESP]) Build() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockClientBuilder[REQ, RESP])(nil).Build))
}

// Use mocks base method.
func (m *MockClientBuilder[REQ, RESP]) Use(middleware Middleware[REQ, RESP]) ClientBuilder[REQ, RESP] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Use", middleware)
	ret0, _ := ret[0].(ClientBuilder[REQ, RESP])
	return ret0
}

// Use indicates an expected call of Use.
func (mr *MockClientBuilderMockRecorder[REQ, RESP]) Use(middleware any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Use", reflect.TypeOf((*MockClientBuilder[REQ, RESP])(nil).Use), middleware)
}

// UseMany mocks base method.
func (m *MockClientBuilder[REQ, RESP]) UseMany(middlewares ...Middleware[REQ, RESP]) ClientBuilder[REQ, RESP] {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range middlewares {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UseMany", varargs...)
	ret0, _ := ret[0].(ClientBuilder[REQ, RESP])
	return ret0
}

// UseMany indicates an expected call of UseMany.
func (mr *MockClientBuilderMockRecorder[REQ, RESP]) UseMany(middlewares ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseMany", reflect.TypeOf((*MockClientBuilder[REQ, RESP])(nil).UseMany), middlewares...)
}

// WithOptions mocks base method.
func (m *MockClientBuilder[REQ, RESP]) WithOptions(options ...http.ClientOption) ClientBuilder[REQ, RESP] {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WithOptions", varargs...)
	ret0, _ := ret[0].(ClientBuilder[REQ, RESP])
	return ret0
}

// WithOptions indicates an expected call of WithOptions.
func (mr *MockClientBuilderMockRecorder[REQ, RESP]) WithOptions(options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithOptions", reflect.TypeOf((*MockClientBuilder[REQ, RESP])(nil).WithOptions), options...)
}
