// Copyright 2021 Cless Li <ClessLee@hotmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Code generated by `codegen -type=int -fullname=CodeExample -namespace=codeexample -doc-output=../../docs/guide/zh-CN/examples/error_code_generated.md -wrapper`; DO NOT EDIT.

package code

import (
	"github.com/ClessLi/component-base/pkg/errors"
)

// Namespace is the error code namespace for this package.
const Namespace = "codeexample"

// init registers error codes defined in this source code to `github.com/ClessLi/component-base/pkg/errors`
func init() {
	errors.Register(errors.DefaultCoder(ErrSuccess, 200, "OK", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/errors/success.md", Namespace))
	errors.Register(errors.DefaultCoder(ErrUnknown, 500, "Contact system administrator with error details for investigation", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/errors/unknown.md", Namespace))
	errors.Register(errors.DefaultCoder(ErrBind, 400, "Check request body and ensure it matches the expected format", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/errors/bind.md", Namespace))
	errors.Register(errors.DefaultCoder(ErrValidation, 400, "Check input parameters and ensure they meet validation requirements", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L20", Namespace))
	errors.Register(errors.DefaultCoder(ErrTokenInvalid, 401, "Provide a valid authentication token", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L21", Namespace))
	errors.Register(errors.DefaultCoder(ErrPageNotFound, 404, "Check the URL path and try again", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L22", Namespace))
	errors.Register(errors.DefaultCoder(ErrRequestTimeout, 408, "Retry request or check network connection", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L23", Namespace))
	errors.Register(errors.DefaultCoder(ErrInvalidParameter, 400, "Check input parameters and ensure they are valid", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L24", Namespace))
	errors.Register(errors.DefaultCoder(ErrDatabase, 500, "Contact system administrator to resolve database connectivity issue", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/errors/database.md", Namespace))
	errors.Register(errors.DefaultCoder(ErrEncrypt, 401, "Provide a valid password that can be encrypted", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L26", Namespace))
	errors.Register(errors.DefaultCoder(ErrSignatureInvalid, 401, "Provide a request with valid signature", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L27", Namespace))
	errors.Register(errors.DefaultCoder(ErrExpired, 401, "Refresh authentication token and try again", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L28", Namespace))
	errors.Register(errors.DefaultCoder(ErrInvalidAuthHeader, 401, "Provide request with valid authorization header", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L29", Namespace))
	errors.Register(errors.DefaultCoder(ErrMissingHeader, 401, "Provide request with valid Authorization header", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L30", Namespace))
	errors.Register(errors.DefaultCoder(ErrUserOrPasswordIncorrect, 401, "Provide valid username and password credentials", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L31", Namespace))
	errors.Register(errors.DefaultCoder(ErrPermissionDenied, 403, "Contact system administrator for required permissions", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L32", Namespace))
	errors.Register(errors.DefaultCoder(ErrAuthnClientInitFailed, 500, "Contact system administrator to initialize authentication client", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L33", Namespace))
	errors.Register(errors.DefaultCoder(ErrAuthClientNotInit, 500, "Contact system administrator to initialize authentication and authorization clients", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L34", Namespace))
	errors.Register(errors.DefaultCoder(ErrConnToAuthServerFailed, 500, "Contact system administrator to check authentication server connectivity", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L35", Namespace))
	errors.Register(errors.DefaultCoder(ErrEncodingFailed, 500, "Check data format and ensure it can be properly encoded", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/errors/encoding.md", Namespace))
	errors.Register(errors.DefaultCoder(ErrDecodingFailed, 500, "Check data format and ensure it can be properly decoded", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L37", Namespace))
	errors.Register(errors.DefaultCoder(ErrInvalidJSON, 500, "Provide data in valid JSON format", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L38", Namespace))
	errors.Register(errors.DefaultCoder(ErrEncodingJSON, 500, "Check JSON data and ensure it can be properly encoded", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L39", Namespace))
	errors.Register(errors.DefaultCoder(ErrDecodingJSON, 500, "Check JSON data and ensure it can be properly decoded", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L40", Namespace))
	errors.Register(errors.DefaultCoder(ErrInvalidYaml, 500, "Provide data in valid YAML format", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L41", Namespace))
	errors.Register(errors.DefaultCoder(ErrEncodingYaml, 500, "Check YAML data and ensure it can be properly encoded", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L42", Namespace))
	errors.Register(errors.DefaultCoder(ErrDecodingYaml, 500, "Check YAML data and ensure it can be properly decoded", "https://github.com/ClessLi/component-base/blob/main/docs/guide/zh-CN/examples/error_code_generated.md#L43", Namespace))
}
