// Copyright 2021 Cless Li <ClessLee@hotmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Code generated by `codegen -wrapper`; DO NOT EDIT.

package code

import (
	"github.com/ClessLi/component-base/pkg/errors"
)

// WithCode creates an error with code and auto-injected namespace.
//
// Example:
//
//	err := WithCode(ErrPageNotFound, "user %s not found", "12345")
//	fmt.Println(err)          // Output: Check the URL path and try again
//	fmt.Printf("%+v\n", err) // Output: user 12345 not found - #0 (codeexample:100006) Check the URL path and try again
func WithCode(code int, format string, args ...interface{}) error {
	return errors.WithCode(Namespace, code, format, args...)
}

// WrapC wraps an error with code and auto-injected namespace.
//
// Example:
//
//	err := WrapC(originalErr, ErrDatabase, "failed to connect to %s", "db")
//	fmt.Println(err)          // Output: Contact system administrator to resolve database connectivity issue
//	fmt.Printf("%+v\n", err) // Output: failed to connect to db - #0 (codeexample:100007) Contact system administrator to resolve database connectivity issue
func WrapC(err error, code int, format string, args ...interface{}) error {
	return errors.WrapC(err, Namespace, code, format, args...)
}

// Wrap returns an error annotating err with a stack trace
// at the point Wrap is called, and the supplied message.
//
// Example:
//
//	err := Wrap(originalErr, "failed to connect to database")
//	fmt.Println(err)          // Output: failed to connect to database
//	fmt.Printf("%+v\n", err) // Output: failed to connect to database - stack trace details
func Wrap(err error, message string) error {
	return errors.Wrap(err, message)
}

// Wrapf returns an error annotating err with a stack trace
// at the point Wrapf is called, and the format specifier.
//
// Example:
//
//	err := Wrapf(originalErr, "failed to write to %s", "/var/log")
//	fmt.Println(err)          // Output: failed to write to /var/log
//	fmt.Printf("%+v\n", err) // Output: failed to write to /var/log - stack trace details
func Wrapf(err error, format string, args ...interface{}) error {
	return errors.Wrapf(err, format, args...)
}

// New returns an error with the supplied message.
// New also records the stack trace at the point it was called.
//
// Example:
//
//	err := New("invalid email format")
//	fmt.Println(err)          // Output: invalid email format
//	fmt.Printf("%+v\n", err) // Output: invalid email format - stack trace details
func New(message string) error {
	return errors.New(message)
}

// Errorf formats according to a format specifier and returns the string
// as a value that satisfies error.
// Errorf also records the stack trace at the point it was called.
//
// Example:
//
//	err := Errorf("connection timeout after %d seconds", 30)
//	fmt.Println(err)          // Output: connection timeout after 30 seconds
//	fmt.Printf("%+v\n", err) // Output: connection timeout after 30 seconds - stack trace details
func Errorf(format string, args ...interface{}) error {
	return errors.Errorf(format, args...)
}

// WithStack annotates err with a stack trace.
//
// Example:
//
//	err := WithStack(originalErr)
//	fmt.Println(err)          // Output: original error message
//	fmt.Printf("%+v\n", err) // Output: original error message - stack trace details
func WithStack(err error) error {
	return errors.WithStack(err)
}

// WithMessage annotates err with a new message.
//
// Example:
//
//	err := WithMessage(originalErr, "failed to parse request body")
//	fmt.Println(err)          // Output: failed to parse request body
//	fmt.Printf("%+v\n", err) // Output: failed to parse request body - stack trace details
func WithMessage(err error, message string) error {
	return errors.WithMessage(err, message)
}

// WithMessagef annotates err with a formatted message.
//
// Example:
//
//	err := WithMessagef(originalErr, "failed to encode %s response", "JSON")
//	fmt.Println(err)          // Output: failed to encode JSON response
//	fmt.Printf("%+v\n", err) // Output: failed to encode JSON response - stack trace details
func WithMessagef(err error, format string, args ...interface{}) error {
	return errors.WithMessagef(err, format, args...)
}

// Cause returns the underlying cause of the error.
//
// Example:
//
//	cause := Cause(wrappedErr)
//	fmt.Println(cause)          // Output: root cause message
//	fmt.Printf("%+v\n", cause) // Output: root cause message - stack trace details
func Cause(err error) error {
	return errors.Cause(err)
}

// NewAggregate converts a slice of errors into an Aggregate interface.
//
// Example:
//
//	agg := NewAggregate([]error{err1, err2})
//	fmt.Println(agg)          // Output: [error1 message, error2 message]
//	fmt.Printf("%+v\n", agg) // Output: [error1 details, error2 details]
func NewAggregate(errlist []error) errors.Aggregate {
	return errors.NewAggregate(errlist)
}

// FilterOut removes all errors that match any of the matchers from the input error.
//
// Example:
//
//	filtered := FilterOut(agg, func(err error) bool {
//		return IsCode(err, ErrPageNotFound)
//	})
//	fmt.Println(filtered)
func FilterOut(err error, fns ...errors.Matcher) error {
	return errors.FilterOut(err, fns...)
}

// Flatten takes an Aggregate and flattens them all into a single Aggregate, recursively.
//
// Example:
//
//	flattened := Flatten(nestedAgg)
//	fmt.Println(flattened)
func Flatten(agg errors.Aggregate) errors.Aggregate {
	return errors.Flatten(agg)
}

// Reduce will return err or, if err is an Aggregate and only has one item, the first item.
//
// Example:
//
//	reduced := Reduce(agg)
//	fmt.Println(reduced)
func Reduce(err error) error {
	return errors.Reduce(err)
}

// AggregateGoroutines runs the provided functions in parallel, stuffing all non-nil errors into the returned Aggregate.
//
// Example:
//
//	agg := AggregateGoroutines(
//		func() error { return doWork1() },
//		func() error { return doWork2() },
//	)
//	if agg != nil {
//		fmt.Println(agg)
//	}
func AggregateGoroutines(funcs ...func() error) errors.Aggregate {
	return errors.AggregateGoroutines(funcs...)
}

// IsCode reports whether any error in err's chain contains the given error code
// within the specified namespace.
//
// Example:
//
//	if IsCode(err, ErrPageNotFound) {
//		fmt.Println("Page not found")
//	}
func IsCode(err error, code int) bool {
	return errors.IsCode(err, Namespace, code)
}

// Is reports whether any error in err's chain matches target.
//
// Example:
//
//	if Is(err, io.EOF) {
//		fmt.Println("End of stream")
//	}
func Is(err, target error) bool {
	return errors.Is(err, target)
}

// As finds the first error in err's chain that matches target, and if so, sets
// target to that error value and returns true.
//
// Example:
//
//	var target *CustomError
//	if As(err, &target) {
//		fmt.Println(target.Message)
//	}
func As(err error, target interface{}) bool {
	return errors.As(err, target)
}

// Unwrap returns the result of calling the Unwrap method on err, if err's
// type contains an Unwrap method returning error.
// Otherwise, Unwrap returns nil.
//
// Example:
//
//	unwrapped := Unwrap(wrappedErr)
//	fmt.Println(unwrapped)
func Unwrap(err error) error {
	return errors.Unwrap(err)
}
