// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ClessLi/component-base/pkg/sort_map (interfaces: SortMap,MapList,MapIndexes)
//
// Generated by this command:
//
//	mockgen -self_package=github.com/ClessLi/component-base/pkg/sort_map -destination=mock_sort_map.go -package=sort_map github.com/ClessLi/component-base/pkg/sort_map SortMap,MapList,MapIndexes
//

// Package sort_map is a generated GoMock package.
package sort_map

import (
	cmp "cmp"
	iter "iter"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	yaml "gopkg.in/yaml.v3"
)

// MockSortMap is a mock of SortMap interface.
type MockSortMap[K cmp.Ordered, V any] struct {
	ctrl     *gomock.Controller
	recorder *MockSortMapMockRecorder[K, V]
	isgomock struct{}
}

// MockSortMapMockRecorder is the mock recorder for MockSortMap.
type MockSortMapMockRecorder[K cmp.Ordered, V any] struct {
	mock *MockSortMap[K, V]
}

// NewMockSortMap creates a new mock instance.
func NewMockSortMap[K cmp.Ordered, V any](ctrl *gomock.Controller) *MockSortMap[K, V] {
	mock := &MockSortMap[K, V]{ctrl: ctrl}
	mock.recorder = &MockSortMapMockRecorder[K, V]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSortMap[K, V]) EXPECT() *MockSortMapMockRecorder[K, V] {
	return m.recorder
}

// Get mocks base method.
func (m *MockSortMap[K, V]) Get(key K) (V, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(V)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSortMapMockRecorder[K, V]) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSortMap[K, V])(nil).Get), key)
}

// Indexes mocks base method.
func (m *MockSortMap[K, V]) Indexes() iter.Seq[int] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Indexes")
	ret0, _ := ret[0].(iter.Seq[int])
	return ret0
}

// Indexes indicates an expected call of Indexes.
func (mr *MockSortMapMockRecorder[K, V]) Indexes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Indexes", reflect.TypeOf((*MockSortMap[K, V])(nil).Indexes))
}

// Keys mocks base method.
func (m *MockSortMap[K, V]) Keys() iter.Seq[K] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Keys")
	ret0, _ := ret[0].(iter.Seq[K])
	return ret0
}

// Keys indicates an expected call of Keys.
func (mr *MockSortMapMockRecorder[K, V]) Keys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keys", reflect.TypeOf((*MockSortMap[K, V])(nil).Keys))
}

// MarshalJSON mocks base method.
func (m *MockSortMap[K, V]) MarshalJSON() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshalJSON")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarshalJSON indicates an expected call of MarshalJSON.
func (mr *MockSortMapMockRecorder[K, V]) MarshalJSON() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshalJSON", reflect.TypeOf((*MockSortMap[K, V])(nil).MarshalJSON))
}

// MarshalYAML mocks base method.
func (m *MockSortMap[K, V]) MarshalYAML() (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshalYAML")
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarshalYAML indicates an expected call of MarshalYAML.
func (mr *MockSortMapMockRecorder[K, V]) MarshalYAML() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshalYAML", reflect.TypeOf((*MockSortMap[K, V])(nil).MarshalYAML))
}

// Range mocks base method.
func (m *MockSortMap[K, V]) Range() iter.Seq2[K, V] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Range")
	ret0, _ := ret[0].(iter.Seq2[K, V])
	return ret0
}

// Range indicates an expected call of Range.
func (mr *MockSortMapMockRecorder[K, V]) Range() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Range", reflect.TypeOf((*MockSortMap[K, V])(nil).Range))
}

// RangeWithIndex mocks base method.
func (m *MockSortMap[K, V]) RangeWithIndex() iter.Seq2[int, V] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RangeWithIndex")
	ret0, _ := ret[0].(iter.Seq2[int, V])
	return ret0
}

// RangeWithIndex indicates an expected call of RangeWithIndex.
func (mr *MockSortMapMockRecorder[K, V]) RangeWithIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RangeWithIndex", reflect.TypeOf((*MockSortMap[K, V])(nil).RangeWithIndex))
}

// RemoveByKey mocks base method.
func (m *MockSortMap[K, V]) RemoveByKey(key K) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveByKey", key)
}

// RemoveByKey indicates an expected call of RemoveByKey.
func (mr *MockSortMapMockRecorder[K, V]) RemoveByKey(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveByKey", reflect.TypeOf((*MockSortMap[K, V])(nil).RemoveByKey), key)
}

// Set mocks base method.
func (m *MockSortMap[K, V]) Set(key K, value V) (V, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, value)
	ret0, _ := ret[0].(V)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Set indicates an expected call of Set.
func (mr *MockSortMapMockRecorder[K, V]) Set(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockSortMap[K, V])(nil).Set), key, value)
}

// UnmarshalJSON mocks base method.
func (m *MockSortMap[K, V]) UnmarshalJSON(arg0 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalJSON", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmarshalJSON indicates an expected call of UnmarshalJSON.
func (mr *MockSortMapMockRecorder[K, V]) UnmarshalJSON(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalJSON", reflect.TypeOf((*MockSortMap[K, V])(nil).UnmarshalJSON), arg0)
}

// UnmarshalYAML mocks base method.
func (m *MockSortMap[K, V]) UnmarshalYAML(value *yaml.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalYAML", value)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmarshalYAML indicates an expected call of UnmarshalYAML.
func (mr *MockSortMapMockRecorder[K, V]) UnmarshalYAML(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalYAML", reflect.TypeOf((*MockSortMap[K, V])(nil).UnmarshalYAML), value)
}

// MockMapList is a mock of MapList interface.
type MockMapList[V any] struct {
	ctrl     *gomock.Controller
	recorder *MockMapListMockRecorder[V]
	isgomock struct{}
}

// MockMapListMockRecorder is the mock recorder for MockMapList.
type MockMapListMockRecorder[V any] struct {
	mock *MockMapList[V]
}

// NewMockMapList creates a new mock instance.
func NewMockMapList[V any](ctrl *gomock.Controller) *MockMapList[V] {
	mock := &MockMapList[V]{ctrl: ctrl}
	mock.recorder = &MockMapListMockRecorder[V]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapList[V]) EXPECT() *MockMapListMockRecorder[V] {
	return m.recorder
}

// Append mocks base method.
func (m *MockMapList[V]) Append(value V) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", value)
	ret0, _ := ret[0].(int)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockMapListMockRecorder[V]) Append(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockMapList[V])(nil).Append), value)
}

// Get mocks base method.
func (m *MockMapList[V]) Get(index int) (V, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", index)
	ret0, _ := ret[0].(V)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMapListMockRecorder[V]) Get(index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMapList[V])(nil).Get), index)
}

// Indexes mocks base method.
func (m *MockMapList[V]) Indexes() iter.Seq[int] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Indexes")
	ret0, _ := ret[0].(iter.Seq[int])
	return ret0
}

// Indexes indicates an expected call of Indexes.
func (mr *MockMapListMockRecorder[V]) Indexes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Indexes", reflect.TypeOf((*MockMapList[V])(nil).Indexes))
}

// InsertToEmpty mocks base method.
func (m *MockMapList[V]) InsertToEmpty(value V) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertToEmpty", value)
	ret0, _ := ret[0].(int)
	return ret0
}

// InsertToEmpty indicates an expected call of InsertToEmpty.
func (mr *MockMapListMockRecorder[V]) InsertToEmpty(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertToEmpty", reflect.TypeOf((*MockMapList[V])(nil).InsertToEmpty), value)
}

// MarshalJSON mocks base method.
func (m *MockMapList[V]) MarshalJSON() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshalJSON")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarshalJSON indicates an expected call of MarshalJSON.
func (mr *MockMapListMockRecorder[V]) MarshalJSON() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshalJSON", reflect.TypeOf((*MockMapList[V])(nil).MarshalJSON))
}

// MarshalYAML mocks base method.
func (m *MockMapList[V]) MarshalYAML() (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshalYAML")
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarshalYAML indicates an expected call of MarshalYAML.
func (mr *MockMapListMockRecorder[V]) MarshalYAML() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshalYAML", reflect.TypeOf((*MockMapList[V])(nil).MarshalYAML))
}

// Range mocks base method.
func (m *MockMapList[V]) Range() iter.Seq2[int, V] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Range")
	ret0, _ := ret[0].(iter.Seq2[int, V])
	return ret0
}

// Range indicates an expected call of Range.
func (mr *MockMapListMockRecorder[V]) Range() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Range", reflect.TypeOf((*MockMapList[V])(nil).Range))
}

// Set mocks base method.
func (m *MockMapList[V]) Set(index int, value V) (V, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", index, value)
	ret0, _ := ret[0].(V)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Set indicates an expected call of Set.
func (mr *MockMapListMockRecorder[V]) Set(index, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockMapList[V])(nil).Set), index, value)
}

// UnmarshalJSON mocks base method.
func (m *MockMapList[V]) UnmarshalJSON(arg0 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalJSON", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmarshalJSON indicates an expected call of UnmarshalJSON.
func (mr *MockMapListMockRecorder[V]) UnmarshalJSON(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalJSON", reflect.TypeOf((*MockMapList[V])(nil).UnmarshalJSON), arg0)
}

// UnmarshalYAML mocks base method.
func (m *MockMapList[V]) UnmarshalYAML(value *yaml.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalYAML", value)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmarshalYAML indicates an expected call of UnmarshalYAML.
func (mr *MockMapListMockRecorder[V]) UnmarshalYAML(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalYAML", reflect.TypeOf((*MockMapList[V])(nil).UnmarshalYAML), value)
}

// MockMapIndexes is a mock of MapIndexes interface.
type MockMapIndexes[K cmp.Ordered] struct {
	ctrl     *gomock.Controller
	recorder *MockMapIndexesMockRecorder[K]
	isgomock struct{}
}

// MockMapIndexesMockRecorder is the mock recorder for MockMapIndexes.
type MockMapIndexesMockRecorder[K cmp.Ordered] struct {
	mock *MockMapIndexes[K]
}

// NewMockMapIndexes creates a new mock instance.
func NewMockMapIndexes[K cmp.Ordered](ctrl *gomock.Controller) *MockMapIndexes[K] {
	mock := &MockMapIndexes[K]{ctrl: ctrl}
	mock.recorder = &MockMapIndexesMockRecorder[K]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapIndexes[K]) EXPECT() *MockMapIndexesMockRecorder[K] {
	return m.recorder
}

// GetKey mocks base method.
func (m *MockMapIndexes[K]) GetKey(idx int) K {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKey", idx)
	ret0, _ := ret[0].(K)
	return ret0
}

// GetKey indicates an expected call of GetKey.
func (mr *MockMapIndexesMockRecorder[K]) GetKey(idx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKey", reflect.TypeOf((*MockMapIndexes[K])(nil).GetKey), idx)
}

// Insert mocks base method.
func (m *MockMapIndexes[K]) Insert(key K) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Insert", key)
}

// Insert indicates an expected call of Insert.
func (mr *MockMapIndexesMockRecorder[K]) Insert(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockMapIndexes[K])(nil).Insert), key)
}

// Keys mocks base method.
func (m *MockMapIndexes[K]) Keys() iter.Seq[int] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Keys")
	ret0, _ := ret[0].(iter.Seq[int])
	return ret0
}

// Keys indicates an expected call of Keys.
func (mr *MockMapIndexesMockRecorder[K]) Keys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keys", reflect.TypeOf((*MockMapIndexes[K])(nil).Keys))
}

// Range mocks base method.
func (m *MockMapIndexes[K]) Range() iter.Seq2[int, K] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Range")
	ret0, _ := ret[0].(iter.Seq2[int, K])
	return ret0
}

// Range indicates an expected call of Range.
func (mr *MockMapIndexesMockRecorder[K]) Range() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Range", reflect.TypeOf((*MockMapIndexes[K])(nil).Range))
}

// Remove mocks base method.
func (m *MockMapIndexes[K]) Remove(key K) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", key)
}

// Remove indicates an expected call of Remove.
func (mr *MockMapIndexesMockRecorder[K]) Remove(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockMapIndexes[K])(nil).Remove), key)
}
