// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ClessLi/component-base/pkg/sort_map (interfaces: SortMap,MapIndexes)
//
// Generated by this command:
//
//	mockgen -self_package=github.com/ClessLi/component-base/pkg/sort_map -destination=mock_sort_map.go -package=sort_map github.com/ClessLi/component-base/pkg/sort_map SortMap,MapIndexes
//

// Package sort_map is a generated GoMock package.
package sort_map

import (
	cmp "cmp"
	iter "iter"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSortMap is a mock of SortMap interface.
type MockSortMap[K cmp.Ordered, V any] struct {
	ctrl     *gomock.Controller
	recorder *MockSortMapMockRecorder[K, V]
	isgomock struct{}
}

// MockSortMapMockRecorder is the mock recorder for MockSortMap.
type MockSortMapMockRecorder[K cmp.Ordered, V any] struct {
	mock *MockSortMap[K, V]
}

// NewMockSortMap creates a new mock instance.
func NewMockSortMap[K cmp.Ordered, V any](ctrl *gomock.Controller) *MockSortMap[K, V] {
	mock := &MockSortMap[K, V]{ctrl: ctrl}
	mock.recorder = &MockSortMapMockRecorder[K, V]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSortMap[K, V]) EXPECT() *MockSortMapMockRecorder[K, V] {
	return m.recorder
}

// GetByKey mocks base method.
func (m *MockSortMap[K, V]) GetByKey(key K) (V, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKey", key)
	ret0, _ := ret[0].(V)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetByKey indicates an expected call of GetByKey.
func (mr *MockSortMapMockRecorder[K, V]) GetByKey(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKey", reflect.TypeOf((*MockSortMap[K, V])(nil).GetByKey), key)
}

// Indexes mocks base method.
func (m *MockSortMap[K, V]) Indexes() iter.Seq[int] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Indexes")
	ret0, _ := ret[0].(iter.Seq[int])
	return ret0
}

// Indexes indicates an expected call of Indexes.
func (mr *MockSortMapMockRecorder[K, V]) Indexes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Indexes", reflect.TypeOf((*MockSortMap[K, V])(nil).Indexes))
}

// Insert mocks base method.
func (m *MockSortMap[K, V]) Insert(key K, value V) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockSortMapMockRecorder[K, V]) Insert(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockSortMap[K, V])(nil).Insert), key, value)
}

// Keys mocks base method.
func (m *MockSortMap[K, V]) Keys() iter.Seq[K] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Keys")
	ret0, _ := ret[0].(iter.Seq[K])
	return ret0
}

// Keys indicates an expected call of Keys.
func (mr *MockSortMapMockRecorder[K, V]) Keys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keys", reflect.TypeOf((*MockSortMap[K, V])(nil).Keys))
}

// Range mocks base method.
func (m *MockSortMap[K, V]) Range() iter.Seq2[K, V] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Range")
	ret0, _ := ret[0].(iter.Seq2[K, V])
	return ret0
}

// Range indicates an expected call of Range.
func (mr *MockSortMapMockRecorder[K, V]) Range() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Range", reflect.TypeOf((*MockSortMap[K, V])(nil).Range))
}

// RangeWithIndex mocks base method.
func (m *MockSortMap[K, V]) RangeWithIndex() iter.Seq2[int, V] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RangeWithIndex")
	ret0, _ := ret[0].(iter.Seq2[int, V])
	return ret0
}

// RangeWithIndex indicates an expected call of RangeWithIndex.
func (mr *MockSortMapMockRecorder[K, V]) RangeWithIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RangeWithIndex", reflect.TypeOf((*MockSortMap[K, V])(nil).RangeWithIndex))
}

// RemoveByKey mocks base method.
func (m *MockSortMap[K, V]) RemoveByKey(key K) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveByKey", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveByKey indicates an expected call of RemoveByKey.
func (mr *MockSortMapMockRecorder[K, V]) RemoveByKey(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveByKey", reflect.TypeOf((*MockSortMap[K, V])(nil).RemoveByKey), key)
}

// MockMapIndexes is a mock of MapIndexes interface.
type MockMapIndexes[K cmp.Ordered] struct {
	ctrl     *gomock.Controller
	recorder *MockMapIndexesMockRecorder[K]
	isgomock struct{}
}

// MockMapIndexesMockRecorder is the mock recorder for MockMapIndexes.
type MockMapIndexesMockRecorder[K cmp.Ordered] struct {
	mock *MockMapIndexes[K]
}

// NewMockMapIndexes creates a new mock instance.
func NewMockMapIndexes[K cmp.Ordered](ctrl *gomock.Controller) *MockMapIndexes[K] {
	mock := &MockMapIndexes[K]{ctrl: ctrl}
	mock.recorder = &MockMapIndexesMockRecorder[K]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapIndexes[K]) EXPECT() *MockMapIndexesMockRecorder[K] {
	return m.recorder
}

// Insert mocks base method.
func (m *MockMapIndexes[K]) Insert(key K) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Insert", key)
}

// Insert indicates an expected call of Insert.
func (mr *MockMapIndexesMockRecorder[K]) Insert(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockMapIndexes[K])(nil).Insert), key)
}

// Keys mocks base method.
func (m *MockMapIndexes[K]) Keys() iter.Seq[int] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Keys")
	ret0, _ := ret[0].(iter.Seq[int])
	return ret0
}

// Keys indicates an expected call of Keys.
func (mr *MockMapIndexesMockRecorder[K]) Keys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keys", reflect.TypeOf((*MockMapIndexes[K])(nil).Keys))
}

// Range mocks base method.
func (m *MockMapIndexes[K]) Range() iter.Seq2[int, K] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Range")
	ret0, _ := ret[0].(iter.Seq2[int, K])
	return ret0
}

// Range indicates an expected call of Range.
func (mr *MockMapIndexesMockRecorder[K]) Range() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Range", reflect.TypeOf((*MockMapIndexes[K])(nil).Range))
}

// Remove mocks base method.
func (m *MockMapIndexes[K]) Remove(key K) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", key)
}

// Remove indicates an expected call of Remove.
func (mr *MockMapIndexesMockRecorder[K]) Remove(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockMapIndexes[K])(nil).Remove), key)
}
